vich_uploader:
    db_driver: orm
    
    mappings:
        paintings_images:
            uri_prefix: /images/paintings
            upload_destination: '%kernel.project_dir%/public/images/paintings'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
